# Generated by Django 4.0.6 on 2022-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_predictions_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teams',
            name='ranking',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='teams',
            unique_together={('ranking', 'round', 'team')},
        ),
    ]
