# Generated by Django 4.0.6 on 2022-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_predictions_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='index',
            field=models.CharField(max_length=50),
        ),
    ]
