# Generated by Django 4.0.6 on 2022-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
