# Generated by Django 4.0.6 on 2022-11-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
