# Generated by Django 4.0.6 on 2022-11-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
